import React from 'react'
import { WiDaySunny,
    WiDaySunnyOvercast,
    WiCloud,
    WiCloudy,
    WiFog,
    WiShowers,
    WiSleet,
    WiSnowWind,
    WiRain } from 'weather-icons-react';
const size = 120
const color = '#fff'
export const weatherIcons = {
    "113": <WiDaySunny size={size} color={color} />,
    "116": <WiDaySunnyOvercast size={size} color={color} />,
    "119": <WiCloud size={size} color={color} />,
    "122": <WiCloudy size={size} color={color} />,
    "143": <WiFog size={size} color={color} />,
    "176": <WiShowers size={size} color={color} />,
    "179": <WiSleet size={size} color={color} />,
    "182": <WiSleet size={size} color={color} />,
    "185": <WiSleet size={size} color={color} />,
    "200": <WiShowers size={size} color={color} />,
    "227": <WiSnowWind size={size} color={color} />,
    "230": <WiSnowWind size={size} color={color} />,
    "248": <WiFog size={size} color={color} />,
    "260": <WiFog size={size} color={color} />,
    "263": <WiShowers size={size} color={color} />,
    "266": <WiRain size={size} color={color} />,
    "281": <WiSleet size={size} color={color} />,
    "284": <WiRain size={size} color={color} />,
    "293": <WiRain size={size} color={color} />,
    "296": <WiShowers size={size} color={color} />,
    "299": <WiRain size={size} color={color} />,
    "302": <WiRain size={size} color={color} />,
    "305": <WiRain size={size} color={color} />,
    "308": <WiSleet size={size} color={color} />,
    "311": <WiSleet size={size} color={color} />,
    "314": <WiSleet size={size} color={color} />,
    "317": <WiSnowWind size={size} color={color} />,
    "320": <WiSnowWind size={size} color={color} />,
    "323": <WiSnowWind size={size} color={color} />,
    "326": <WiSnowWind size={size} color={color} />,
    "329": <WiSnowWind size={size} color={color} />,
    "332": <WiSnowWind size={size} color={color} />,
    "335": <WiSnowWind size={size} color={color} />,
    "338": <WiSnowWind size={size} color={color} />,
    "350": <WiSnowWind size={size} color={color} />,
    "353": <WiShowers size={size} color={color} />,
    "356": <WiShowers size={size} color={color} />,
    "359": <WiRain size={size} color={color} />,
    "362": <WiSleet size={size} color={color} />,
    "365": <WiShowers size={size} color={color} />,
    "368": <WiShowers size={size} color={color} />,
    "371": <WiRain size={size} color={color} />,
    "374": <WiShowers size={size} color={color} />,
    "377": <WiShowers size={size} color={color} />,
    "386": <WiShowers size={size} color={color} />,
    "389": <WiShowers size={size} color={color} />,
    "392": <WiRain size={size} color={color} />,
    "395": <WiRain size={size} color={color} />
}